name: my first github action

on:
  push:
    branches:
      - feature/github-actions-ci

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Intentional failure
        run: exit 1
     # - name: Say hello
      #  run: echo "Hello Uday, Github Actions is working!"

      - name: Show current directory
        run: pwd

      - name: Show files
        run: ls -la

      - name: Show git Version
        run: git --version
